name: build, deploy task in main server
on:
  push:
    branches:
      - main
jobs:
  build_docker:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t aisyah78/23_ci-cd:1.0 .
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
        - name: push to docker hub
          run: docker push aisyah78/23_ci-cd:1.0