name: build, deploy task in main server
on:
  push:
    branches:
      - main
jobs:
  build_docker:
    name: build and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t aisyah78/23_CI-CD:1.0